rename flag

diff --git a/share/tparts_build/tparts_build b/share/tparts_build/tparts_build
--- a/share/tparts_build/tparts_build
+++ b/share/tparts_build/tparts_build
@@ -3,21 +3,21 @@ set -e
 
 usage() {
 cat << EOF
-usage: $0 -t|--template TEMPLATE -p|--parts PARTS [-n|--filename-template FILE] [-h|--help]
+usage: $0 -t|--template TEMPLATE -p|--values VALUES [-n|--filename-template FILE] [-h|--help]
 
 This script takes template and it's parts to compose an HTML document.
 
 OPTIONS:
   -t|--template TEMPLATE      The template directory.
-  -p|--parts PARTS            ":" delimeted list of template parts,
-                              ordered from generic to document specific.
+  -e|--values VALUES          ":" delimeted list of template value directory paths,
+                              ordered from global to document specific scope.
   -f|template-filename FILE   Custom filename for template.
                               Defaults to "template.html" if not provided.
   -h|--help                   Show this message.
 EOF
 }
 
-DIR_TEMPLATE="" TPARTS_DIR_LIST="" FILENAME_TEMPLATE=""
+DIR_TEMPLATE="" VALUES_DIR_LIST="" FILENAME_TEMPLATE=""
 
 if [ $# -eq 0 ]; then usage; exit 1; fi
 
@@ -26,9 +26,9 @@ while [ ! $# -eq 0 ]; do
 		-t|--template)
       if [ "$2" ]; then DIR_TEMPLATE="$2"; shift
       else echo '-t|--template requires a value'; exit 1; fi;;
-		-p|--parts)
-      if [ "$2" ]; then TPARTS_DIR_LIST="$2"; shift
-      else echo '-p|--parts requires a value'; exit 1; fi;;
+		-e|--values)
+      if [ "$2" ]; then VALUES_DIR_LIST="$2"; shift
+      else echo '-p|--values requires a value'; exit 1; fi;;
 		-f|template-filename)
       if [ "$2" ]; then FILENAME_TEMPLATE="$2"; shift
       else echo '-f|template-filename requires a value'; exit 1; fi;;
@@ -38,10 +38,10 @@ while [ ! $# -eq 0 ]; do
 done
 
 if [ -z "$DIR_TEMPLATE" ]; then echo '-t|--template value is required'; exit 1; fi
-if [ -z "$TPARTS_DIR_LIST" ]; then echo '-p|--parts value is required'; exit 1; fi
+if [ -z "$VALUES_DIR_LIST" ]; then echo '-p|--values value is required'; exit 1; fi
 
 export AWKPATH=$DIR_TEMPLATE:$AWKPATH
 
 awk \
   -f $(cd -P -- "$(dirname -- "$0")" && pwd -P)/tparts_build.awk \
-  -v dir_template="$DIR_TEMPLATE" -v tparts_dir_list="$TPARTS_DIR_LIST" -v filename_template="$FILENAME_TEMPLATE"
+  -v dir_template="$DIR_TEMPLATE" -v tparts_values_dir_list="$VALUES_DIR_LIST" -v filename_template="$FILENAME_TEMPLATE"
